<a href="https://colab.research.google.com/github/ulya1202/Data-science-projects/blob/main/Sentiment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Import

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.metrics import f1_score ,recall_score ,precision_score , accuracy_score, classification_report

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, PolynomialFeatures,OneHotEncoder,FunctionTransformer
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.compose import ColumnTransformer
# from sklearn.decomposition import PCA
# from sklearn.manifold import TSNE, LocallyLinearEmbedding,  LocallyLinearEmbedding
from sklearn.feature_extraction.text import TfidfVectorizer

# from sklearn.metrics import make_scorer, silhouette_score  #

# from sklearn.naive_bayes import MultinomialNB,ComplementNB
# from sklearn.cluster import KMeans
# from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor, ExtraTreesClassifier,VotingClassifier, BaggingClassifier,AdaBoostClassifier,GradientBoostingClassifier, StackingClassifier
# from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
# , cross_val_score, GridSearchCV, StratifiedKFold
# from sklearn.linear_model import LinearRegression, SGDRegressor,SGDClassifier,LogisticRegression
# from sklearn.svm import LinearSVC, SVC

# from imblearn.over_sampling import SMOTE
# from imblearn.pipeline import Pipeline as bpline

In [ ]:
!kaggle datasets download -d  mdismielhossenabir/sentiment-analysis

Dataset URL: https://www.kaggle.com/datasets/mdismielhossenabir/sentiment-analysis
License(s): MIT
Downloading sentiment-analysis.zip to /content
  0% 0.00/14.3k [00:00<?, ?B/s]
100% 14.3k/14.3k [00:00<00:00, 17.5MB/s]

In [ ]:
!unzip sentiment-analysis.zip

Archive:  sentiment-analysis.zip
  inflating: sentiment_analysis.csv

In [ ]:
df=pd.read_csv('sentiment_analysis.csv')

In [ ]:
df

,Year,Month,Day,Time of Tweet,text,sentiment,Platform
0,2018,8,18,morning,What a great day!!! Looks like dream.,positive,Twitter
1,2018,8,18,noon,"I feel sorry, I miss you here in the sea beach",positive,Facebook
2,2017,8,18,night,Don't angry me,negative,Facebook
3,2022,6,8,morning,We attend in the class just for listening teac...,negative,Facebook
4,2022,6,8,noon,"Those who want to go, let them go",negative,Instagram
...,...,...,...,...,...,...,...
494,2015,10,18,night,"According to , a quarter of families under six...",negative,Twitter
495,2021,2,25,morning,the plan to not spend money is not going well,negative,Instagram
496,2022,5,30,noon,uploading all my bamboozle pictures of facebook,neutral,Facebook
497,2018,8,10,night,congratulations ! you guys finish a month ear...,positive,Twitter
498,2019,3,25,morning,"actually, I wish I was back in Tahoe. I miss...",negative,Instagram

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.dtypes

Year              int64
Month             int64
Day               int64
Time of Tweet    object
text             object
sentiment        object
Platform         object
dtype: object

# Preprocessing

In [ ]:
y=df['sentiment'].copy()
X=df.drop(['sentiment'], axis=1)
X_train_full, X_test, y_train_full, y_test=train_test_split(X,y, test_size=0.15, random_state=42)
X_train, X_val, y_train, y_val=train_test_split(X_train_full,y_train_full, test_size=0.15, random_state=42)

In [ ]:
text_col=['text']
num_col=X_train.select_dtypes(include=[np.number]).columns
cat_col=X_train.select_dtypes(exclude=[np.number]).columns.difference(text_col)

In [ ]:
cat_pipeline=make_pipeline(
    SimpleImputer(strategy='most_frequent'),
    OneHotEncoder(handle_unknown='ignore', sparse_output=False)
)

num_pipeline=make_pipeline(
    SimpleImputer(strategy='median'),
    StandardScaler()
)

In [ ]:
transformer=ColumnTransformer([
    ('cat',cat_pipeline,cat_col ),
    ('num',num_pipeline, num_col),

],remainder='drop')

In [ ]:

transformer.fit(X_train)

ColumnTransformer(transformers=[('cat',
                                 Pipeline(steps=[('simpleimputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('onehotencoder',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False))]),
                                 Index(['Platform', 'Time of Tweet'], dtype='object')),
                                ('num',
                                 Pipeline(steps=[('simpleimputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('standardscaler',
                                                  StandardScaler())]),
                                 Index(['Year', 'Month', 'Day'], dtype='object'))])

In [ ]:
c=transformer.transform(X_train)

In [ ]:
tv=TfidfVectorizer()

In [ ]:
tv.fit(X_train['text'])

TfidfVectorizer()

In [ ]:
X_train_tex=tv.transform(X_train['text'])

In [ ]:
X_train_transfored_full=np.concatenate((c,X_train_tex.toarray()),axis=1)

# models

In [ ]:
model_2=tf.keras.Sequential([
    tf.keras.layers.Input(shape=(X_train_transfored_full.shape[1],)),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Dense(512, kernel_initializer='he_normal'),
    tf.keras.layers.PReLU(),
    tf.keras.layers.BatchNormalization(),
    # tf.keras.layers.Dropout(0.3),

    tf.keras.layers.Dense(256, kernel_initializer='he_normal',use_bias=False),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.LeakyReLU(),


    tf.keras.layers.Dense(128, kernel_initializer='he_normal', use_bias=False),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.LeakyReLU(),


    tf.keras.layers.Dense(64, kernel_initializer='he_normal',use_bias=False),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.LeakyReLU(),

    tf.keras.layers.Dense(32, kernel_initializer='he_normal',use_bias=False),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.LeakyReLU(),

    tf.keras.layers.Dense(16, kernel_initializer='he_normal',use_bias=False),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.LeakyReLU(),

    tf.keras.layers.Dense(8, kernel_initializer='he_normal',use_bias=False),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.LeakyReLU(),

    tf.keras.layers.Dense(4, kernel_initializer='he_normal',use_bias=False),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.LeakyReLU(),

    tf.keras.layers.Dense(2, kernel_initializer='he_normal',use_bias=False),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.LeakyReLU(),

    tf.keras.layers.Dense(3, activation='softmax')
])

In [ ]:


model_2.compile(
    loss='sparse_categorical_crossentropy',
    optimizer=tf.keras.optimizers.SGD(learning_rate=0.001),
    metrics=['accuracy']
)

In [ ]:
from sklearn.preprocessing import LabelEncoder

# Create a LabelEncoder object
label_encoder = LabelEncoder()

y_train_encoded = label_encoder.fit_transform(y_train)
y_val_encoded = label_encoder.transform(y_val)
y_test_encoded=label_encoder.transform(y_test)

In [ ]:
model_2.fit(X_train_transfored_full, y_train_encoded, epochs=100)

Epoch 1/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.7560 - loss: 0.7772
Epoch 2/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - accuracy: 0.7478 - loss: 0.7543
Epoch 3/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7266 - loss: 0.7562
Epoch 4/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7513 - loss: 0.7540
Epoch 5/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7395 - loss: 0.7817
Epoch 6/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7106 - loss: 0.7493
Epoch 7/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7552 - loss: 0.7705
Epoch 8/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7408 - loss: 0.7866
Epoch 9/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7407 - loss: 0.7619
Epoch 10/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8052 - loss: 0.7373
Epoch 11/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7343 - loss: 0.7790
Epoch 12/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7560 - loss: 0.7346
Epoch 13/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7460 - loss: 0.7502
Epoch 14/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7780 - loss: 0.7294
Epoch 15/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8151 - loss: 0.7232
Epoch 16/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7901 - loss: 0.7223
Epoch 17/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8299 - loss: 0.7054
Epoch 18/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7690 - loss: 0.7380
Epoch 19/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8112 - loss: 0.7176
Epoch 20/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7362 - loss: 0.7811
Epoch 21/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7552 - loss: 0.7204
Epoch 22/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7724 - loss: 0.7390
Epoch 23/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7900 - loss: 0.7202
Epoch 24/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8410 - loss: 0.6755
Epoch 25/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7846 - loss: 0.7144
Epoch 26/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7908 - loss: 0.7060
Epoch 27/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7731 - loss: 0.7458
Epoch 28/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7765 - loss: 0.6944
Epoch 29/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8041 - loss: 0.7050
Epoch 30/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7911 - loss: 0.7037
Epoch 31/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8125 - loss: 0.6988
Epoch 32/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8106 - loss: 0.6928
Epoch 33/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7904 - loss: 0.6940
Epoch 34/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8623 - loss: 0.6584
Epoch 35/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8307 - loss: 0.6829
Epoch 36/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7582 - loss: 0.7337
Epoch 37/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8489 - loss: 0.6864
Epoch 38/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8086 - loss: 0.6829
Epoch 39/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8890 - loss: 0.6682
Epoch 40/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8412 - loss: 0.6426
Epoch 41/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8769 - loss: 0.6767
Epoch 42/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8418 - loss: 0.6723
Epoch 43/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.8357 - loss: 0.6832
Epoch 44/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.8677 - loss: 0.6404
Epoch 45/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.8514 - loss: 0.6686
Epoch 46/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.8367 - loss: 0.6681
Epoch 47/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8306 - loss: 0.6651
Epoch 48/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.8370 - loss: 0.6626
Epoch 49/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.8485 - loss: 0.6352
Epoch 50/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.8640 - loss: 0.6371
Epoch 51/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.8511 - loss: 0.6673
Epoch 52/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8885 - loss: 0.6357
Epoch 53/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8872 - loss: 0.6422
Epoch 54/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8116 - loss: 0.6793
Epoch 55/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8354 - loss: 0.6331
Epoch 56/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8019 - loss: 0.6726
Epoch 57/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8726 - loss: 0.6311
Epoch 58/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9183 - loss: 0.6135
Epoch 59/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8309 - loss: 0.6595
Epoch 60/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8932 - loss: 0.6214
Epoch 61/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8585 - loss: 0.6436
Epoch 62/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8899 - loss: 0.5953
Epoch 63/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8691 - loss: 0.6240
Epoch 64/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8711 - loss: 0.6212
Epoch 65/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8859 - loss: 0.6171
Epoch 66/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8973 - loss: 0.6056
Epoch 67/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8709 - loss: 0.6214
Epoch 68/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8570 - loss: 0.6202
Epoch 69/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9094 - loss: 0.6053
Epoch 70/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8633 - loss: 0.6243
Epoch 71/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8736 - loss: 0.6396
Epoch 72/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9117 - loss: 0.5992
Epoch 73/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8906 - loss: 0.5793
Epoch 74/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8760 - loss: 0.6178
Epoch 75/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8722 - loss: 0.6071
Epoch 76/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9414 - loss: 0.5616
Epoch 77/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8981 - loss: 0.6105
Epoch 78/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9007 - loss: 0.5964
Epoch 79/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9054 - loss: 0.5920
Epoch 80/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8779 - loss: 0.5961
Epoch 81/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9187 - loss: 0.5703
Epoch 82/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9205 - loss: 0.5682
Epoch 83/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9047 - loss: 0.5748
Epoch 84/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9121 - loss: 0.5773
Epoch 85/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9219 - loss: 0.5768
Epoch 86/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9268 - loss: 0.5771
Epoch 87/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9302 - loss: 0.5612
Epoch 88/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9223 - loss: 0.5712
Epoch 89/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8980 - loss: 0.5988
Epoch 90/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9169 - loss: 0.5726
Epoch 91/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9340 - loss: 0.5756
Epoch 92/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8871 - loss: 0.5731
Epoch 93/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8902 - loss: 0.5874
Epoch 94/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9208 - loss: 0.5512
Epoch 95/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8777 - loss: 0.5999
Epoch 96/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9031 - loss: 0.5696
Epoch 97/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8934 - loss: 0.5775
Epoch 98/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.8910 - loss: 0.5608
Epoch 99/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8898 - loss: 0.5584
Epoch 100/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9306 - loss: 0.5569

##X_test

In [ ]:
X_test_transformed=transformer.transform(X_test)

In [ ]:
X_test_tex=tv.transform(X_test['text'])

In [ ]:
X_test_full=np.concatenate((X_test_transformed,X_test_tex.toarray()), axis=1)

In [ ]:
test_p=model_2.predict(X_test_full).argmax(axis=1)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

In [ ]:
print(classification_report(y_test_encoded, test_p))

              precision    recall  f1-score   support

           0       0.18      0.21      0.19        14
           1       0.42      0.36      0.39        22
           2       0.38      0.38      0.38        24

    accuracy                           0.33        60
   macro avg       0.32      0.32      0.32        60
weighted avg       0.35      0.33      0.34        60

# again

In [ ]:
X=df['text'].copy()
y=df['sentiment'].copy()

In [ ]:
X_train_full, X_test, y_train_full, y_test=train_test_split(X,y, test_size=0.15, random_state=42)
X_train, X_val, y_train, y_val=train_test_split(X_train_full,y_train_full, test_size=0.15, random_state=42)

In [ ]:
tfid=TfidfVectorizer()

In [ ]:
X_train_transformed=tfid.fit_transform(X_train)
X_val_transformed=tfid.transform(X_val)
X_test_transformed=tfid.transform(X_test)

In [ ]:
from sklearn.preprocessing import LabelEncoder


label_encoder = LabelEncoder()


y_train_encoded = label_encoder.fit_transform(y_train)
y_val_encoded = label_encoder.transform(y_val)
y_test_encoded=label_encoder.transform(y_test)

In [ ]:
import tensorflow as tf

In [ ]:
# tfid = tf.keras.layers.TextVectorization(max_tokens=max_tokens, output_mode='int', output_sequence_length=output_dim)


model_2=tf.keras.Sequential([
    tf.keras.layers.Input(shape=(X_train_transformed.shape[1],)),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Dense(512, kernel_initializer='he_normal'),
    tf.keras.layers.PReLU(),
    tf.keras.layers.BatchNormalization(),
    # tf.keras.layers.Dropout(0.3),

    tf.keras.layers.Dense(256, kernel_initializer='he_normal',use_bias=False),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.LeakyReLU(),


    tf.keras.layers.Dense(128, kernel_initializer='he_normal', use_bias=False),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.LeakyReLU(),


    tf.keras.layers.Dense(64, kernel_initializer='he_normal',use_bias=False),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.LeakyReLU(),

    tf.keras.layers.Dense(32, kernel_initializer='he_normal',use_bias=False),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.LeakyReLU(),

    tf.keras.layers.Dense(16, kernel_initializer='he_normal',use_bias=False),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.LeakyReLU(),

    tf.keras.layers.Dense(8, kernel_initializer='he_normal',use_bias=False),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.LeakyReLU(),

    tf.keras.layers.Dense(4, kernel_initializer='he_normal',use_bias=False),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.LeakyReLU(),

    tf.keras.layers.Dense(2, kernel_initializer='he_normal',use_bias=False),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.LeakyReLU(),

    tf.keras.layers.Dense(3, activation='softmax')
])

In [ ]:


model_2.compile(
    loss='sparse_categorical_crossentropy',
    optimizer=tf.keras.optimizers.SGD(learning_rate=0.001),
    metrics=['accuracy']
)

In [ ]:

checkpoint_cb = tf.keras.callbacks.ModelCheckpoint("my_checkpoints.weights.h5",
                                                   save_weights_only=True)

In [ ]:
model_2.fit(X_train_transformed, y_train_encoded, epochs=10, callbacks=[checkpoint_cb],validation_data=(X_val_transformed, y_val_encoded))

Epoch 1/10

Exception ignored in: <function _xla_gc_callback at 0x7cdf889807c0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/jax/_src/lib/__init__.py", line 96, in _xla_gc_callback
    def _xla_gc_callback(*args):

KeyboardInterrupt:

9/9 ━━━━━━━━━━━━━━━━━━━━ 64s 114ms/step - accuracy: 0.9954 - loss: 0.1115 - val_accuracy: 0.3137 - val_loss: 1.9116
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9847 - loss: 0.1413 - val_accuracy: 0.3137 - val_loss: 1.9159
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 1.0000 - loss: 0.1288 - val_accuracy: 0.3137 - val_loss: 1.9113
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9939 - loss: 0.1372 - val_accuracy: 0.3137 - val_loss: 1.9083
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 45ms/step - accuracy: 0.9993 - loss: 0.1090 - val_accuracy: 0.3137 - val_loss: 1.9072
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9929 - loss: 0.1416 - val_accuracy: 0.3137 - val_loss: 1.9020
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9939 - loss: 0.1202 - val_accuracy: 0.3137 - val_loss: 1.9062
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9939 - loss: 0.1180 - val_accuracy: 0.3333 - val_loss: 1.9055
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.9952 - loss: 0.1195 - val_accuracy: 0.3137 - val_loss: 1.9075
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 75ms/step - accuracy: 0.9952 - loss: 0.1152 - val_accuracy: 0.3137 - val_loss: 1.9082

In [ ]:
y_pred=model_2.predict(X_test_transformed)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step

In [ ]:
y_pred.argmax(axis=1)

array([1, 2, 1, 0, 1, 1, 1, 0, 0, 1, 0, 2, 2, 2, 1, 2, 0, 1, 0, 0, 0, 2,
       2, 2, 2, 1, 2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 0, 2, 2, 2, 2,
       2, 2, 1, 2, 2, 2, 1, 1, 2, 0, 1, 2, 2, 1, 0, 2])

In [ ]:
print(classification_report(y_test_encoded, y_pred.argmax(axis=1)))

              precision    recall  f1-score   support

           0       0.21      0.21      0.21        14
           1       0.55      0.50      0.52        22
           2       0.54      0.58      0.56        24

    accuracy                           0.47        60
   macro avg       0.43      0.43      0.43        60
weighted avg       0.47      0.47      0.47        60

## testing based my texts

In [ ]:
my_text=['I did not liked your attitide it was negative']
my=tfid.transform(my_text)
model_2.predict(my).argmax()

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step

1

In [ ]:
my_text=['it was bad']
my=tfid.transform(my_text)
model_2.predict(my).argmax()

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step

0

In [ ]:
y

0      positive
1      positive
2      negative
3      negative
4      negative
         ...
494    negative
495    negative
496     neutral
497    positive
498    negative
Name: sentiment, Length: 394, dtype: object

In [ ]:
y_train_encoded[0]

2

In [ ]:
y_train.iloc[0]

'positive'

In [ ]:
y_train.iloc[1],y_train_encoded[1]

('neutral', 1)

In [ ]:
my_text=['it was good']
my=tfid.transform(my_text)
model_2.predict(my).argmax()

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step

2

In [ ]:
my_text=['it was super']
my=tfid.transform(my_text)
model_2.predict(my).argmax()

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step

2

In [ ]:
my_text=['i think i will pass exam veery well.']
my=tfid.transform(my_text)
model_2.predict(my).argmax()

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step

2

In [ ]:
my_text=['he thinks that he will not pass exam.']
my=tfid.transform(my_text)
model_2.predict(my).argmax()

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 189ms/step

0

In [ ]:
my_text=['i am sick']
my=tfid.transform(my_text)
model_2.predict(my).argmax()

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step

0

In [ ]:
my_text=['i am alive']#------------------------------------------------------------------------!!!!
my=tfid.transform(my_text)
model_2.predict(my).argmax()

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

0

In [ ]:
my_text=['he is in bad situtaion']
my=tfid.transform(my_text)
model_2.predict(my).argmax()

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

0

In [ ]:
my_text=['i hate']
my=tfid.transform(my_text)
model_2.predict(my).argmax()

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 423ms/step

1

In [ ]:
my_text=['i am dead']#------------------------------------------------------------------------!!!!
my=tfid.transform(my_text)
model_2.predict(my).argmax()

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 209ms/step

2